# ------------------------------------------------------------------------------------------------------------------------
# 4. Pipeline with a variable file AND a hard-coded parameters file
# ------------------------------------------------------------------------------------------------------------------------
trigger: none
pool:
  vmImage: ubuntu-latest

jobs:
 - job:
   displayName: Deploy Bicep

   variables:
     - template: vars/var-common-01.yml

   steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        azureResourceManagerConnection: 'Demo Service Connection'
        resourceGroupName: $(resourceGroupName)
        location: $(location)
        csmFile: '$(bicepPath)/$(bicepFileName)'
        csmParametersFile: '$(bicepPath)/storageaccount-hardcoded.bicepparam'
