# ------------------------------------------------------------------------------------------------------------------------
# 5. Pipeline with a variable file merging into a parameters file
# ------------------------------------------------------------------------------------------------------------------------
trigger: none
pool:
  vmImage: ubuntu-latest

jobs:
 - job:
   displayName: Deploy Bicep

   variables:
     - template: vars/var-common-01.yml
     - name: bicepPath
       value: '$(Build.SourcesDirectory)/infra/bicep'
     - name: bicepFile
       value: 'storageaccount.bicep'
     - name: parameterFile
       value: 'storageaccount-variables.bicepparam'
     - name: bicepFilePath
       value: '$(bicepPath)/$(bicepFile)'
     - name: parameterFilePath
       value: '$(bicepPath)/$(parameterFile)'

   steps:
    - task: qetza.replacetokens.replacetokens-task.replacetokens@3
      displayName: 'Update Parameter File'
      inputs:
        targetFiles: $(parameterFilePath)
        tokenPrefix: '#{'
        tokenSuffix: '}#'

    - task: CmdLine@2
      displayName: Display Parameter File Contents
      continueOnError: true
      inputs:
        script: |
          echo "Bicep File Name: $(bicepFilePath)"
          echo "Parameter File Name: $(parameterFilePath)"
          cat $(parameterFilePath)

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy Resources'
      inputs:
        azureResourceManagerConnection: 'Demo Service Connection'
        resourceGroupName: $(resourceGroupName)
        location: $(location)
        csmFile: $(bicepFilePath)
        csmParametersFile: $(parameterFilePath)
