# ------------------------------------------------------------------------------------------------------------------------
# 7. Pipeline calling a reusable template, adding source scanning stages
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)

trigger: none

pool:
  vmImage: ubuntu-latest

# ----------------------------------------------------------------------------------------------------
variables:
  - template: vars/var-common-02.yml

# ----------------------------------------------------------------------------------------------------
parameters:
  - name: runGHASScan
    displayName: Run GHAS Scan
    type: boolean
    default: true
  - name: runMSDevSecOpsScan
    displayName: Run MS DevSecOps Scan
    type: boolean
    default: true

# ----------------------------------------------------------------------------------------------------
stages:
  - template: templates/07-template-scan-code.yml
    parameters:
      runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
      runGHASScan: ${{ parameters.runGHASScan }}

  - template: templates/07-template-deploy-bicep.yml
    parameters:
      bicepPath: 'infra/bicep'
      bicepFile: 'storageaccount.bicep'
      parameterFile: 'storageaccount-variables.bicepparam'
