# ------------------------------------------------------------------------------------------------------------------------
# 8. Pipeline calling a reusable templates to scan, build, resource, and deploy app
# ------------------------------------------------------------------------------------------------------------------------
# This pipelines needs a variable group named "Demo.DadABase"
# To create this variable groups, customize and run this command in the Azure Cloud Shell.
# Alternatively, you could define these variables in the Azure DevOps Portal on each pipeline, but a variable group is a more repeatable and scriptable way to do it.
#
#   az pipelines variable-group create 
#     --organization=https://dev.azure.com/<yourAzDOOrg>/ 
#     --project='<yourAzDOProject>' 
#     --name Demo.DadABase 
#     --variables 
#         apiKey='<yourapiKey>'
#         adDomain='yourDomain.onmicrosoft.com'
#         adTenantId='yourTenantId'
#         adClientId='yourClientId'
#         adInstance='yourLoginInstance'
# ------------------------------------------------------------------------------------------------------------------------

name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)

trigger: none

pool:
  vmImage: ubuntu-latest

# ----------------------------------------------------------------------------------------------------
variables:
  - group: Demo.DadABase
  - template: vars/var-common-08.yml

# ----------------------------------------------------------------------------------------------------
parameters:
  - name: runGHASScan
    displayName: Run GHAS Scan
    type: boolean
    default: true
  - name: runMSDevSecOpsScan
    displayName: Run MS DevSecOps Scan
    type: boolean
    default: true

# ----------------------------------------------------------------------------------------------------
stages:
  - template: templates/08-template-scan-code-advanced.yml
    parameters:
      runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
      runGHASScan: ${{ parameters.runGHASScan }}

  - template: templates/08-template-build-webapp.yml

  - template: templates/08-template-deploy-bicep.yml
    parameters:
      environmentName: 'DEV'
      bicepPath: 'Labs/Module_10_CICD_Pipelines/bicep'
      bicepFile: 'main-web-app.bicep'
      parameterFile: 'main-web-app.bicepparam'

  - template: templates/08-template-deploy-webapp.yml
    parameters:
      environmentName: 'DEV'
