# ----------------------------------------------------------------------------------------------------
# Pipeline example that uses templates from another repository
# ----------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: ubuntu-latest

# ----------------------------------------------------------------------------------------------------
trigger:
  - none

# ----------------------------------------------------------------------------------------------------
# Bring in the library of templates
# ----------------------------------------------------------------------------------------------------
resources:
  repositories:
      - repository: template.library          # the internal pseudonym for in this pipeline
        type: git
        name: DevOpsLibrary/template.library  # the name of some other repository in your project
        ref: master

# ----------------------------------------------------------------------------------------------------
parameters:
  - name: runGHASScan
    displayName: Run GHAS Scan
    type: boolean
    default: false
  - name: runMSDevSecOpsScan
    displayName: Run MS DevSecOps Scan
    type: boolean
    default: false

# ----------------------------------------------------------------------------------------------------
stages:
- ${{ if or(eq(lower(parameters.runMSDevSecOpsScan), 'true'), eq(lower(parameters.runGHASScan), 'true')) }}:
  - stage: ScanApplication
    displayName: Scan Application
    jobs:
    - template: scan-code-template.yml@template.library
      parameters:
        environmentName: 'DEMO'
        runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
        runGHASScan: ${{ parameters.runGHASScan }}

  - stage: BuildApplication
    displayName: Build Application
    dependsOn: ScanApplication
    jobs:
    - template: build-function-template.yml@template.library
      parameters:
        environmentName: 'DEV'

# ----------------------------------------------------------------------------------------------------
- ${{ if and(eq(lower(parameters.runMSDevSecOpsScan), 'false'), eq(lower(parameters.runGHASScan), 'false')) }}:
  - stage: BuildApplication
    displayName: Build Application
    jobs:
    - template: build-function-template.yml@template.library
      parameters:
        environmentName: 'DEV'
