# ----------------------------------------------------------------------------------------------------
# Code Scanning Template
# ----------------------------------------------------------------------------------------------------
# GitHub Advanced Security For Azure DevOps
# To enable this, you must enable GHAzDO for this repository in your Azure DevOps Project
# ----------------------------------------------------------------------------------------------------
# Microsoft Secure DevOps Scan
# To enable this, you must add Azure DevOps Extension to your Azure DevOps Organization
# See https://marketplace.visualstudio.com/items?itemName=ms-securitydevops.microsoft-security-devops-azdevops
# ----------------------------------------------------------------------------------------------------
parameters:
- name: environmentName
  default: 'DEV'
- name: runGHASScan
  default: 'true'
- name: runMSDevSecOpsScan
  default: 'true'

# ----------------------------------------------------------------------------------------------------
stages:
  - stage: ScanStage
    displayName: Scan Code
    jobs:
    - deployment: CodeScanDeployment
      displayName: Initialize Code Scans 
      environment: ${{ parameters.environmentName }}

    # ----------------------------------------------------------------------------------------------------
    - ${{ if eq(lower(parameters.runGHASScan), 'true') }}:
      - job: GHASScanJob
        displayName: GHAS Scan Job 
        variables:
          - template: ../vars/var-source-location-app.yml

        # Very basic simple example that works most of the time...
        steps:
        - task: AdvancedSecurity-Codeql-Init@1
          inputs:
            languages: 'csharp'

        - task: DotNetCoreCLI@2
          inputs:
            command: 'restore'
            projects: '$(Build.SourcesDirectory)/$(appProjectFolderName)/*.csproj'

        - task: AdvancedSecurity-Dependency-Scanning@1

        - task: AdvancedSecurity-Codeql-Autobuild@1

        - task: AdvancedSecurity-Codeql-Analyze@1

        - task: AdvancedSecurity-Publish@1 

    # ----------------------------------------------------------------------------------------------------
    - ${{ if eq(lower(parameters.runMSDevSecOpsScan), 'true') }}:
      - job: DevSecOpsScanJob
        displayName: DevSecOps Scan Job 
        steps:
        - task: UseDotNet@2
          displayName: 'Use dotnet 8.0'
          inputs:
            version: 8.0.x

        - task: MicrosoftSecurityDevOps@1
          displayName: 'Run Microsoft Security DevOps'
          continueOnError: true
